archlinux PKGBUILD reads automatically from latest tag

diff --git a/archlinux/PKGBUILD b/archlinux/PKGBUILD
--- a/archlinux/PKGBUILD
+++ b/archlinux/PKGBUILD
@@ -1,4 +1,4 @@
-# Maintainer: Khalid Eldehairy <khalid@kdehairy.com>
+# Maintainer: Khalid Eldehairy <khalid # kdehairy / com>
 _pacparser_pkgver=1.3.7
 _txdbus_pkgver=1.0.14
 _systemd_pkgver=0.9.5
@@ -16,15 +16,17 @@ depends=('python>=3.6' 'python-twisted' 'python-pyopenssl' 'libsystemd' 'network
 makedepends=('git' 'python-pyasn1' 'python-pyasn1-modules' 'python-attrs' 'python-idna')
 provides=('python-pacparser')
 install=${pkgname%-git}.install
-source=("${pkgname%-git}::git+https://github.com/tkluck/pac4cli.git#branch=archlinux-package"
+source=("${pkgname%-git}::git+https://github.com/tkluck/pac4cli.git"
 		"https://github.com/pacparser/pacparser/archive/${_pacparser_pkgver}.tar.gz"
 		"https://github.com/cocagne/txdbus/archive/${_txdbus_pkgver}.tar.gz"
 		"https://files.pythonhosted.org/packages/source/s/systemd/systemd-${_systemd_pkgver}.tar.gz"
 		"https://files.pythonhosted.org/packages/source/s/service_identity/service_identity-${_service_identity_pkgver}.tar.gz")
 md5sums=('SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP')
+
 pkgver() {
 	cd "$srcdir/${pkgname%-git}"
-	printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
+	LATEST_TAG=$(git describe --abbrev=0 --match 'v*' 2>/dev/null)
+	printf "%s" "${LATEST_TAG#*v}"
 }
 
 build() {
@@ -48,9 +50,6 @@ package() {
 
 	#systemd
 	cd "${srcdir}/systemd-${_systemd_pkgver}"
-	
-	# The maintainer does not have releases published yet.
-	# This commit matches the version on PyPI
 	python3 setup.py install --root="${pkgdir}/" --prefix=/usr --optimize=1
 
 	#service_identity
@@ -59,5 +58,11 @@ package() {
 
 	#package pac4cli
 	cd "${srcdir}/${pkgname%-git}"
+	LATEST_TAG=$(git describe --abbrev=0 --match 'v*' 2>/dev/null)	# get latest release tag
+	if [[ "x${LATEST_TAG}" == "x" ]]; then
+		echo "Could not find any releases to build."
+		exit 1;
+	fi
+	git checkout ${LATEST_TAG}										# checkout latest release tag
 	PYTHON=python3 make pythonsitedir=/usr/lib/python3.6/site-packages DESTDIR="${pkgdir}" prefix=/usr install
 }
